import type { Scenario } from "../scenario";

/**
 * `chronicle-demo/orbit` — a fictional real-time workspace-sync service.
 * Its four-year history is scripted to exercise every part of the pipeline:
 * framework adoption, tests + CI, a monorepo migration, a debt spiral in the
 * sync engine (cycle, oversized file, fix pressure, TODOs), and a v2 cleanup.
 */
export const orbitScenario: Scenario = {
  repository: {
    id: "chronicle-demo/orbit",
    owner: "chronicle-demo",
    name: "orbit",
    description:
      "Fictional demo — a real-time workspace sync service with a scripted, instructive history.",
    url: "https://github.com/chronicle-demo/orbit",
    primaryLanguage: "TypeScript",
    languages: { TypeScript: 82, JavaScript: 8, YAML: 6, Markdown: 4 },
    stars: 0,
    forks: 0,
    defaultBranch: "main",
    createdAt: "2021-01-05T09:00:00Z",
    pushedAt: "2024-06-20T16:00:00Z",
  },
  authors: [
    { login: "arivera", name: "Alex Rivera" },
    { login: "mchen", name: "Mira Chen" },
    { login: "dokafor", name: "Dami Okafor" },
    { login: "ktanaka", name: "Kenji Tanaka" },
    { login: "pnovak", name: "Petra Novak" },
    { login: "lsilva", name: "Lucas Silva" },
    { login: "claurent", name: "Camille Laurent" },
    { login: "jkim", name: "Jisoo Kim" },
  ],
  phases: [
    {
      name: "Founding",
      from: "2021-01-05",
      to: "2021-03-20",
      commitsPerWeek: 4,
      churn: [20, 120],
      authors: ["arivera", "mchen"],
      messages: [
        "Initial project scaffold",
        "Wire up HTTP server and config loading",
        "Add request logging middleware",
        "Sketch document model",
        "Set up TypeScript build",
        "Add basic error handling",
      ],
      adds: [
        { path: "package.json", loc: 42, at: 0 },
        { path: "README.md", loc: 60, at: 0 },
        { path: "src/index.ts", loc: 80, at: 0 },
        { path: "src/server.ts", loc: 140, at: 0.1 },
        { path: "src/config.ts", loc: 70, at: 0.15 },
        { path: "src/logger.ts", loc: 55, at: 0.3 },
      ],
      focus: ["src/index.ts", "src/server.ts", "src/config.ts"],
      depsAdd: ["express", "typescript"],
      imports: [
        { from: "src/index.ts", to: "src/server.ts" },
        { from: "src/server.ts", to: "src/config.ts" },
        { from: "src/server.ts", to: "src/logger.ts" },
      ],
    },
    {
      name: "Core features",
      from: "2021-03-20",
      to: "2021-08-15",
      commitsPerWeek: 6,
      churn: [40, 260],
      authors: ["arivera", "mchen", "dokafor"],
      messages: [
        "Add document CRUD routes",
        "Implement sync engine skeleton",
        "Add operational transform for concurrent edits",
        "Persist documents in Postgres",
        "Add change queue with backpressure",
        "Validate payloads with zod",
        "Add cursor positions to sync payloads",
        "Handle reconnect with resume tokens",
      ],
      fixRatio: 0.15,
      adds: [
        { path: "src/api/routes.ts", loc: 180, at: 0.05 },
        { path: "src/api/handlers.ts", loc: 240, at: 0.1 },
        { path: "src/sync/engine.ts", loc: 320, at: 0.2 },
        { path: "src/sync/transform.ts", loc: 210, at: 0.3 },
        { path: "src/sync/queue.ts", loc: 150, at: 0.35 },
        { path: "src/store/db.ts", loc: 190, at: 0.4 },
        { path: "src/store/migrations.ts", loc: 90, at: 0.45 },
      ],
      focus: [
        "src/api/handlers.ts",
        "src/sync/engine.ts",
        "src/sync/transform.ts",
        "src/store/db.ts",
      ],
      depsAdd: ["pg", "zod", "ws"],
      imports: [
        { from: "src/index.ts", to: "src/api/routes.ts" },
        { from: "src/api/routes.ts", to: "src/api/handlers.ts" },
        { from: "src/api/handlers.ts", to: "src/sync/engine.ts" },
        { from: "src/api/handlers.ts", to: "src/store/db.ts" },
        { from: "src/sync/engine.ts", to: "src/sync/transform.ts" },
        { from: "src/sync/engine.ts", to: "src/sync/queue.ts" },
        { from: "src/sync/engine.ts", to: "src/store/db.ts" },
      ],
    },
    {
      name: "Tests and CI",
      from: "2021-08-15",
      to: "2021-11-10",
      commitsPerWeek: 5,
      churn: [30, 180],
      authors: ["mchen", "dokafor", "arivera"],
      messages: [
        "Add jest and first engine tests",
        "Test operational transform edge cases",
        "Add API integration tests",
        "Run tests in CI",
        "Add lint step to pipeline",
        "Cover queue overflow behavior",
      ],
      adds: [
        { path: "tests/engine.test.ts", loc: 220, at: 0.05 },
        { path: "tests/transform.test.ts", loc: 180, at: 0.15 },
        { path: "tests/api.test.ts", loc: 160, at: 0.3 },
        { path: ".github/workflows/ci.yml", loc: 48, at: 0.4 },
      ],
      focus: ["tests/engine.test.ts", "src/sync/engine.ts", "tests/api.test.ts"],
      depsAdd: ["jest", "supertest"],
      release: { tag: "v0.3.0", name: "First stable preview" },
    },
    {
      name: "Growth and realtime",
      from: "2021-11-10",
      to: "2022-05-01",
      commitsPerWeek: 11,
      churn: [60, 420],
      authors: ["arivera", "mchen", "dokafor", "ktanaka", "pnovak", "lsilva", "claurent"],
      messages: [
        "Add websocket gateway",
        "Broadcast presence updates",
        "Add awareness of remote cursors",
        "Shard rooms across workers",
        "Add webhook delivery",
        "Rate-limit room joins",
        "Compress sync payloads",
        "Add metrics endpoint",
        "Batch presence diffs",
        "Optimize transform hot path",
      ],
      fixRatio: 0.18,
      adds: [
        { path: "src/realtime/socket.ts", loc: 260, at: 0.05 },
        { path: "src/realtime/presence.ts", loc: 190, at: 0.15 },
        { path: "src/realtime/rooms.ts", loc: 230, at: 0.25 },
        { path: "src/api/webhooks.ts", loc: 170, at: 0.4 },
        { path: "src/metrics.ts", loc: 80, at: 0.5 },
      ],
      focus: [
        "src/realtime/socket.ts",
        "src/realtime/rooms.ts",
        "src/sync/engine.ts",
        "src/sync/transform.ts",
        "src/api/handlers.ts",
      ],
      imports: [
        { from: "src/realtime/socket.ts", to: "src/sync/engine.ts" },
        { from: "src/realtime/socket.ts", to: "src/realtime/presence.ts" },
        { from: "src/realtime/rooms.ts", to: "src/realtime/presence.ts" },
        { from: "src/realtime/socket.ts", to: "src/realtime/rooms.ts" },
        { from: "src/api/webhooks.ts", to: "src/sync/queue.ts" },
      ],
      release: { tag: "v1.0.0", name: "Orbit 1.0" },
    },
    {
      name: "Monorepo migration",
      from: "2022-05-01",
      to: "2022-08-10",
      commitsPerWeek: 7,
      churn: [40, 220],
      authors: ["arivera", "ktanaka", "mchen"],
      messages: [
        "Split server and core into packages",
        "Extract shared protocol types",
        "Move realtime gateway into server package",
        "Set up workspace tooling",
        "Fix cross-package build order",
      ],
      adds: [
        { path: "packages/core/package.json", loc: 30, at: 0.2 },
        { path: "packages/server/package.json", loc: 32, at: 0.2 },
        { path: "packages/protocol/types.ts", loc: 140, at: 0.3 },
        { path: "packages/protocol/package.json", loc: 24, at: 0.3 },
        { path: "packages/core/model/document.ts", loc: 160, at: 0.4 },
        { path: "packages/server/auth/tokens.ts", loc: 140, at: 0.5 },
      ],
      renames: [
        { from: "src/sync/engine.ts", to: "packages/core/sync/engine.ts" },
        { from: "src/sync/transform.ts", to: "packages/core/sync/transform.ts" },
        { from: "src/sync/queue.ts", to: "packages/core/sync/queue.ts" },
        { from: "src/store/db.ts", to: "packages/core/store/db.ts" },
        { from: "src/store/migrations.ts", to: "packages/core/store/migrations.ts" },
        { from: "src/api/routes.ts", to: "packages/server/api/routes.ts" },
        { from: "src/api/handlers.ts", to: "packages/server/api/handlers.ts" },
        { from: "src/api/webhooks.ts", to: "packages/server/api/webhooks.ts" },
        { from: "src/realtime/socket.ts", to: "packages/server/realtime/socket.ts" },
        { from: "src/realtime/presence.ts", to: "packages/server/realtime/presence.ts" },
        { from: "src/realtime/rooms.ts", to: "packages/server/realtime/rooms.ts" },
        { from: "src/server.ts", to: "packages/server/app/server.ts" },
        { from: "src/index.ts", to: "packages/server/app/index.ts" },
      ],
      focus: [
        "packages/core/sync/engine.ts",
        "packages/server/api/handlers.ts",
        "packages/protocol/types.ts",
        "packages/core/model/document.ts",
      ],
      imports: [
        { from: "packages/server/app/server.ts", to: "packages/server/api/routes.ts" },
        { from: "packages/server/app/server.ts", to: "packages/server/realtime/socket.ts" },
        { from: "packages/server/app/server.ts", to: "packages/server/auth/tokens.ts" },
        { from: "packages/server/api/handlers.ts", to: "packages/core/sync/engine.ts" },
        { from: "packages/server/api/handlers.ts", to: "packages/server/auth/tokens.ts" },
        { from: "packages/server/api/handlers.ts", to: "packages/core/model/document.ts" },
        { from: "packages/server/api/handlers.ts", to: "packages/protocol/types.ts" },
        { from: "packages/server/realtime/socket.ts", to: "packages/core/sync/engine.ts" },
        { from: "packages/server/realtime/socket.ts", to: "packages/protocol/types.ts" },
        { from: "packages/core/sync/engine.ts", to: "packages/core/store/db.ts" },
        { from: "packages/core/sync/engine.ts", to: "packages/core/model/document.ts" },
        { from: "packages/core/sync/engine.ts", to: "packages/protocol/types.ts" },
        { from: "packages/core/store/db.ts", to: "packages/core/model/document.ts" },
      ],
    },
    {
      name: "Debt accumulation",
      from: "2022-08-10",
      to: "2023-07-01",
      commitsPerWeek: 8,
      churn: [80, 380],
      authors: ["ktanaka", "arivera", "jkim"],
      messages: [
        "Special-case list reordering in engine",
        "Add feature flags to sync path",
        "Support offline queue replay",
        "Patch transform for nested tables",
        "Add per-org rate limits to engine",
        "Handle schema drift during sync",
        "Add engine hooks for plugins",
        "Workaround for stale presence sessions",
      ],
      fixRatio: 0.42,
      reverts: 4,
      focus: [
        "packages/core/sync/engine.ts",
        "packages/core/sync/engine.ts",
        "packages/core/sync/engine.ts",
        "packages/core/sync/transform.ts",
        "packages/server/api/handlers.ts",
      ],
      todoDelta: 46,
      complexityDrift: 0.35,
      imports: [
        // The cycle that later shows up as a debt signal:
        { from: "packages/core/sync/engine.ts", to: "packages/server/notify/dispatch.ts" },
        { from: "packages/server/notify/dispatch.ts", to: "packages/core/sync/queue.ts" },
        { from: "packages/server/api/webhooks.ts", to: "packages/server/notify/dispatch.ts" },
      ],
      adds: [{ path: "packages/server/notify/dispatch.ts", loc: 130, at: 0.15 }],
    },
    {
      name: "Cleanup and v2",
      from: "2023-07-01",
      to: "2024-06-20",
      commitsPerWeek: 6,
      churn: [50, 260],
      authors: ["arivera", "mchen", "pnovak", "jkim"],
      messages: [
        "Extract plugin runtime from engine",
        "Delete legacy compatibility layer",
        "Add client SDK package",
        "Simplify queue backpressure",
        "Document sync protocol",
        "Type-safe plugin API",
        "Migrate webhooks to outbox pattern",
      ],
      fixRatio: 0.2,
      adds: [
        { path: "packages/client/sdk.ts", loc: 260, at: 0.3 },
        { path: "packages/client/package.json", loc: 26, at: 0.3 },
        { path: "packages/core/plugins/runtime.ts", loc: 180, at: 0.15 },
        { path: "packages/core/plugins/api.ts", loc: 110, at: 0.2 },
        { path: "docs/protocol.md", loc: 220, at: 0.5 },
      ],
      removes: [
        { path: "src/logger.ts", at: 0.1 },
        { path: "src/config.ts", at: 0.1 },
        { path: "src/metrics.ts", at: 0.1 },
      ],
      focus: [
        "packages/core/sync/engine.ts",
        "packages/core/plugins/runtime.ts",
        "packages/client/sdk.ts",
        "packages/server/api/handlers.ts",
      ],
      todoDelta: -10,
      complexityDrift: -0.1,
      imports: [
        { from: "packages/client/sdk.ts", to: "packages/protocol/types.ts" },
        { from: "packages/core/plugins/runtime.ts", to: "packages/protocol/types.ts" },
        { from: "packages/core/plugins/runtime.ts", to: "packages/core/plugins/api.ts" },
        { from: "packages/core/sync/engine.ts", to: "packages/core/plugins/runtime.ts" },
      ],
      release: { tag: "v2.0.0", name: "Orbit 2.0" },
    },
  ],
};
